-- Generated by `pikku db generate` from @pikku/kysely's runtime services.
-- Re-run the command after changing that source.

create table "ai_run_score" ("id" varchar(36) primary key, "run_id" varchar(36) not null references "ai_run" ("run_id") on delete cascade, "scorer_name" varchar(255) not null, "score" real not null, "reason" text, "metadata" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_ai_run_score_run" on "ai_run_score" ("run_id", "created_at");

create table "credential_kek_salts" ("key_version" integer primary key, "salt" varchar(64) not null, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create table "secret_kek_salts" ("key_version" integer primary key, "salt" varchar(64) not null, "created_at" timestamp default CURRENT_TIMESTAMP not null);

ALTER TABLE pikku_roles ADD COLUMN system boolean DEFAULT false NOT NULL;

ALTER TABLE pikku_roles ADD COLUMN declared boolean DEFAULT true NOT NULL;

ALTER TABLE workflow_step ADD COLUMN current_attempt INTEGER;

ALTER TABLE workflow_step_history ADD COLUMN attempt INTEGER;
