-- Generated by `pikku db generate` from @pikku/kysely's runtime services.
-- Re-run the command after changing that source.

create table "agent_message" ("id" varchar(36) primary key, "thread_id" varchar(36) not null references "agent_threads" ("id") on delete cascade, "role" varchar(50) not null, "content" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_message_thread" on "agent_message" ("thread_id", "created_at");

create table "agent_run" ("run_id" varchar(36) primary key, "agent_name" varchar(255) not null, "thread_id" varchar(36) not null references "agent_threads" ("id") on delete cascade, "resource_id" varchar(255) not null, "status" varchar(50) default 'running' not null, "error_message" text, "suspend_reason" text, "missing_rpcs" text, "pending_approvals" text, "usage_input_tokens" integer default 0 not null, "usage_output_tokens" integer default 0 not null, "usage_model" varchar(255) default '' not null, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_run_thread" on "agent_run" ("thread_id", "created_at");

create table "agent_run_score" ("id" varchar(36) primary key, "run_id" varchar(36) not null references "agent_run" ("run_id") on delete cascade, "scorer_name" varchar(255) not null, "score" real not null, "reason" text, "metadata" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_run_score_run" on "agent_run_score" ("run_id", "created_at");

create table "agent_threads" ("id" varchar(36) primary key, "resource_id" varchar(255) not null, "title" text, "metadata" text, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_threads_resource" on "agent_threads" ("resource_id");

create table "agent_tool_call" ("id" varchar(36) primary key, "thread_id" varchar(36) not null references "agent_threads" ("id") on delete cascade, "message_id" varchar(36) not null references "agent_message" ("id") on delete cascade, "run_id" varchar(36), "tool_name" varchar(255) not null, "args" text not null, "result" text, "approval_status" varchar(50), "approval_type" varchar(50), "agent_run_id" varchar(36), "display_tool_name" varchar(255), "display_args" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_tool_call_thread" on "agent_tool_call" ("thread_id");

create index "idx_agent_tool_call_message" on "agent_tool_call" ("message_id");

create table "agent_working_memory" ("id" varchar(255) not null, "scope" varchar(50) not null, "data" text not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null, constraint "agent_working_memory_pk" primary key ("id", "scope"));
