-- Generated by `pikku db generate` from @pikku/kysely's runtime services.
-- Re-run the command after changing that source.

create table "audit" ("audit_id" text primary key, "occurred_at" text not null, "type" text not null, "source" text default 'auto' not null, "outcome" text, "function_id" text, "wire_type" text, "trace_id" text, "transaction_id" text, "query_id" text, "user_id" text, "org_id" text, "pikku_user_id" text, "tables" text, "changed_cols" text, "event" text, "old" text, "data" text);

create index "idx_audit_occurred_at" on "audit" ("occurred_at");

create index "idx_audit_user_id" on "audit" ("user_id");

create index "idx_audit_type" on "audit" ("type");

create table "virtual_user_run" ("run_id" varchar(36) primary key, "persona" varchar(255) not null, "disposition" varchar(50) not null, "seed" bigint not null, "status" varchar(50) default 'running' not null, "goals" text default '[]' not null, "memory" text default '{}' not null, "findings" text default '[]' not null, "intents" text default '[]' not null, "tally" text, "stopped_by" varchar(255), "error" text, "started_by" varchar(255), "created_at" timestamp default CURRENT_TIMESTAMP not null, "finished_at" timestamp);

create index "idx_virtual_user_run_created" on "virtual_user_run" ("created_at");

create index "idx_virtual_user_run_persona" on "virtual_user_run" ("persona", "created_at");

create table "virtual_user_run_step" ("run_id" varchar(36) not null, "step_index" integer not null, "intent_id" varchar(255), "action" text not null, "status" integer, "ok" integer, "response" text, "finding_kinds" text, "tokens_in" integer default 0 not null, "tokens_out" integer default 0 not null, constraint "pk_virtual_user_run_step" primary key ("run_id", "step_index"));

create table "virtual_user_schedule" ("persona" varchar(255) primary key, "enabled" integer default 0 not null, "disposition" varchar(50) not null, "goals" text default '[]' not null, "budget" text, "min_interval_ms" bigint not null, "max_interval_ms" bigint not null, "next_run_at" timestamp not null, "last_run_id" varchar(36), "last_run_at" timestamp);

create index "idx_virtual_user_schedule_due" on "virtual_user_schedule" ("enabled", "next_run_at");
