-- Generated by `pikku db generate` from @pikku/kysely's runtime services.
-- Re-run the command after changing that source.

create table "pikku_feature_flags" ("name" text primary key, "description" text, "any_of" text, "enabled" boolean default false not null, "rollout_percent" integer, "declared" boolean default true not null, "updated_by" text, "note" text, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create table "pikku_feature_flag_overrides" ("flag" text not null references "pikku_feature_flags" ("name") on delete cascade, "subject_id" text not null, "subject_kind" text not null, "enabled" boolean not null, "granted_by" text, "granted_at" timestamp default CURRENT_TIMESTAMP not null, constraint "pikku_feature_flag_overrides_pk" primary key ("flag", "subject_id"));

create table "pikku_analytics_events" ("event_id" text primary key, "name" text not null, "occurred_at" text not null, "source" text not null, "function_id" text, "wire_type" text, "trace_id" text, "user_id" text, "org_id" text, "pikku_user_id" text, "anonymous_id" text, "vendor_ids" text, "consent" text, "props" text);

create index "idx_pikku_analytics_events_occurred_at" on "pikku_analytics_events" ("occurred_at");

create index "idx_pikku_analytics_events_name" on "pikku_analytics_events" ("name");
